### ISSUE TITLE
Rotate icon current location

### ISSUE THREAD

**Issue by aleffabricio** [synw/livemap#2]
Hello how are you? I wanted to ask another question for you, do you know any plugins or do you have a hint on how I move the user's location icon according to the user's rotation on the mobile? for example, if it turns south the icon will also flip, some way to convert the data from the gyroscope or accelerometer in angle to the icon of the main marker

**Comment by aleffabricio** [comment]
Hello, I was able to solve with the plugin https://pub.dev/packages/flutter_compass#-example-tab-, thank you for the beautiful work of the livemap.

**Comment by synw** [comment]
For infothere is a new feature now in the map controller that allows you to autorotate the map from the bearing of the position: use the param `autorotate = true` in the controller
